socket-server:
  host: localhost
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL:update}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessExp: ${JWT_ACCESS_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}